### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by whit537** [timothyfcook/pgh_col#6]
We want one organizational partner to embed this widget on their website. Who will the first one be? :scream: 

 - [ ] recruit a guinea pig
 - [ ] train them to add events via Pgh City of Learning
 - [ ] get events out of API (#1)
 - [ ] format events like we want 'em
 - [ ] have guinea pig add our javascript to their website
 - [ ] celebrate :tada:
